leftnav:
- identifier: 9c277a00-1f00-4039-9537-81d8cf2ea78b
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 035cbabe-684f-4ae4-b662-1b832d177d01
  name: Lecture Notes and LaTeX
  url: /pages/lecture-notes-and-latex
  weight: 20
- identifier: 06b59c24-4a10-442d-92dc-01e67b747c7d
  name: Lecture Files Resource List
  url: /lists/lecture-notes
  weight: 30
